### Importando librerías

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[ 8,  7,  9,  6, 12],
       [ 7, 17,  7,  3,  9]])

In [5]:
arr

array([ 8,  7,  9,  6, 12,  7, 17,  7,  3,  9])

### Max

In [6]:
arr.max()

17

In [7]:
matriz

array([[ 8,  7,  9,  6, 12],
       [ 7, 17,  7,  3,  9]])

In [8]:
matriz.max(1)
matriz.max(0)

array([ 8, 17,  9,  6, 12])

### Argmax

In [9]:
arr.argmax()

6

In [10]:
matriz.argmax(0)

array([0, 1, 0, 0, 0])

### Min

In [11]:
arr.min()

3

In [12]:
matriz.min(0)

array([7, 7, 7, 3, 9])

### Argmin

In [13]:
arr.argmin()

8

In [14]:
matriz.argmin(1)

array([3, 3])

### Ptp

In [15]:
arr

array([ 8,  7,  9,  6, 12,  7, 17,  7,  3,  9])

In [36]:
arr.ptp() 

AttributeError: 'NoneType' object has no attribute 'ptp'

In [17]:
matriz

array([[ 8,  7,  9,  6, 12],
       [ 7, 17,  7,  3,  9]])

In [18]:
matriz.ptp(0)

array([ 1, 10,  2,  3,  3])

In [19]:
matriz.ptp(1)

array([ 6, 14])

### Sort

In [37]:
arr.sort()
arr

AttributeError: 'NoneType' object has no attribute 'sort'

### Percentile

In [21]:
np.percentile(arr,50)

7.5

In [22]:
np.percentile(arr,76)

9.0

### Median

In [23]:
np.median(arr)

7.5

In [24]:
np.median(matriz,1)

array([7., 9.])

### Standard Deviation (std)

In [25]:
np.std(arr) 

3.5846896657869842

In [26]:
arr

array([ 3,  6,  7,  7,  7,  8,  9,  9, 12, 17])

In [27]:
np.std(arr) ** 2

12.850000000000001

### Variance (Var)

In [28]:
np.var(arr)

12.85

### Mean

In [29]:
np.mean(arr)

8.5

### Concatenate

In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [31]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
a.ndim
b.ndim

1

In [ ]:
b = np.expand_dims(b,axis=0)

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b

In [ ]:
np.concatenate((a,b),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### Transpuesta

In [ ]:
b.T

array([[[5]],

       [[6]]])