## Importando la libreria

In [2]:
import numpy as np

### Creando array

In [3]:
arr = np.arange(1,11,)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
trozo_de_arr = arr[0:5] 

In [5]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0])

In [6]:
arr

array([ 0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

## Comando copy

- Copia el objeto de tipo arry, y los hace **distintos**.

In [7]:
arr_copy = arr.copy()

In [8]:
arr_copy

array([ 0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [9]:
arr_copy[0:5] = 100

In [12]:
arr_copy

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

- Son **totalmente distintos** sin importar que tengan los mismo valores.
- Eso es porque como se **gurdan en memoria** de manera diferente.

In [11]:
arr

array([ 0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

> 🎈 Siempre que **queramos modificar** un array y **no afectar el original** usar **.copy()**