## Importando **NumPy**

In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')

## ✅ Condiciones
- Las condiciones nos permiten hacer consultas más específicas.

In [3]:
indice_cond = arr > 5

In [4]:
arr[indice_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [5]:
arr[(arr > 5 ) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [6]:
arr[arr > 5] = 99

In [7]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [8]:
arr[arr != 99]

array([1, 2, 3, 4, 5], dtype=int8)

----

## creando mas array

In [9]:
a = np.random.randint(1,19, size=(2,5))

In [10]:
a

array([[16,  4,  8, 14, 17],
       [16,  6, 12,  6,  9]])

In [11]:
a[(a > 7) & (a<13)]
a[(a == 8) | (a != 13)]

array([16,  4,  8, 14, 17, 16,  6, 12,  6,  9])

In [12]:
f = a.ptp() > 7

In [13]:
a[f]

array([[[16,  4,  8, 14, 17],
        [16,  6, 12,  6,  9]]])