In [1]:
import numpy as np

## **Generando** un array

In [2]:
arr = np.random.randint(1, 4, size=(3,2))
arr

array([[1, 1],
       [2, 1],
       [2, 1]])

## **Ver** la **estructura de un array** 🦄

- Muestra la **cantidad de filas y columnas**

In [3]:
arr.shape

(3, 2)

## **Reformando** la **estructura** de una **array**

- Para la **transforamcion** de una array tenemos que **respetar la cantidad elementos** de la **escructura (x,y)**.


### Ejemplo con arr = np.random.randint(1, 4, size = **(3,2)** )

In [4]:
arr.reshape(1,6) 
arr.reshape(6,1)

array([[1],
       [1],
       [2],
       [1],
       [2],
       [1]])

- Siempre tiene que dar la **misma cantidad de elmentos**

In [5]:
arr = np.random.randint(1,5, size=(4,8))
arr.shape
arr.reshape(16,2)



array([[4, 3],
       [3, 3],
       [3, 1],
       [2, 4],
       [4, 1],
       [4, 1],
       [2, 4],
       [1, 1],
       [4, 2],
       [4, 1],
       [2, 3],
       [4, 1],
       [4, 1],
       [2, 4],
       [2, 3],
       [4, 1]])

- ver como se **reforma** y **organiza** una **estructura** en otro **lenguajes de programacion**

In [6]:
arr
np.reshape(arr,(8,4),'C')

array([[4, 3, 3, 3],
       [3, 1, 2, 4],
       [4, 1, 4, 1],
       [2, 4, 1, 1],
       [4, 2, 4, 1],
       [2, 3, 4, 1],
       [4, 1, 2, 4],
       [2, 3, 4, 1]])

In [7]:
np.reshape(arr,(16,2),'F')

array([[4, 3],
       [4, 2],
       [4, 2],
       [4, 2],
       [3, 1],
       [1, 4],
       [2, 3],
       [1, 3],
       [3, 2],
       [4, 1],
       [4, 4],
       [2, 4],
       [3, 4],
       [1, 1],
       [1, 1],
       [4, 1]])

- La '**A**' hace referencia a mi **OS(Sitema Operativo)**.

In [8]:
np.reshape(arr,(8,4),'A')

array([[4, 3, 3, 3],
       [3, 1, 2, 4],
       [4, 1, 4, 1],
       [2, 4, 1, 1],
       [4, 2, 4, 1],
       [2, 3, 4, 1],
       [4, 1, 2, 4],
       [2, 3, 4, 1]])

> Preferimente usar **'C'** lo organiza por **filas** y **columnas**.

> Para mejor **optimizacion** usar **'A'**


## Reto!!

In [9]:
f = np.random.randint(2,5, size=(32,1))
f
f.shape


(32, 1)

In [10]:
np.reshape(f,(8,4),"C")

array([[3, 3, 4, 2],
       [4, 2, 3, 3],
       [3, 3, 4, 4],
       [3, 3, 3, 3],
       [3, 4, 2, 3],
       [3, 2, 4, 2],
       [3, 2, 4, 3],
       [4, 3, 4, 3]])

In [11]:
np.reshape(f,(8,4),"F")

array([[3, 3, 3, 3],
       [3, 3, 4, 2],
       [4, 4, 2, 4],
       [2, 4, 3, 3],
       [4, 3, 3, 4],
       [2, 3, 2, 3],
       [3, 3, 4, 4],
       [3, 3, 2, 3]])

In [12]:
np.reshape(f,(1,32),"A")

array([[3, 3, 4, 2, 4, 2, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 4, 2, 3, 3, 2,
        4, 2, 3, 2, 4, 3, 4, 3, 4, 3]])

In [13]:
np.reshape(f,(1,32),"C")

array([[3, 3, 4, 2, 4, 2, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 4, 2, 3, 3, 2,
        4, 2, 3, 2, 4, 3, 4, 3, 4, 3]])

In [14]:
np.reshape(f,(1,32),"F")

array([[3, 3, 4, 2, 4, 2, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 4, 2, 3, 3, 2,
        4, 2, 3, 2, 4, 3, 4, 3, 4, 3]])