## Importandon NumPy

In [1]:
import numpy as np

## Operando listas con **Python**

In [2]:
lista = [1, 2, 3]
lista

[1, 2, 3]

In [3]:
lista * 2

[1, 2, 3, 1, 2, 3]

## Operando lista con **NumPy**

In [13]:
arr = np.arange(0, 10)

arr2 = arr.copy() # Copiandoo un arr

arr3 = np.arange(1,5)

## Operaciones 

In [5]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr / 21

array([0.        , 0.04761905, 0.0952381 , 0.14285714, 0.19047619,
       0.23809524, 0.28571429, 0.33333333, 0.38095238, 0.42857143])

In [7]:
arr - 6

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3])

In [8]:
3 ** arr

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [9]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
3 / arr + arr2 

/tmp/ipykernel_21778/4021719164.py:1: RuntimeWarning: divide by zero encountered in true_divide
  3 / arr + arr2


array([       inf, 4.        , 3.5       , 4.        , 4.75      ,
       5.6       , 6.5       , 7.42857143, 8.375     , 9.33333333])

In [11]:
arr / arr2

/tmp/ipykernel_21778/1444868932.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

## Creando **Matriz**

In [12]:
matriz = arr.reshape(shape=(2,5))
matriz2 = matriz.copy()

TypeError: 'shape' is an invalid keyword argument for this function

In [ ]:
matriz 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz + matriz2  

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

> Podemos usar cualqueir operador algebraico 🏆

In [ ]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
np.matmul(matriz,matriz2.T)  

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])